# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, Devops world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your az400new project.
    @echo off
    echo Hello World from %AGENT_NAME%.
    echo My ID is %AGENT_ID%.
    echo AGENT_WORKFOLDER contents: 
    @dir %AGENT_WORKFOLDER%
    echo AGENT_BUILDDIRECTORY contents:
    @dir %AGENT_BUILDDIRECTORY%
    echo BUILD_SOURCESDIRECTORY contents:
    @dir %BUILD_SOURCESDIRECTORY%
    echo Over and out.
    echo See https://virtualvemula.com
  displayName: 'Run a multi-line script'
